### ISSUE TITLE
Add logic to see whether the subnet in the ENIConfig is in the same AZ as the worker node

### ISSUE THREAD

**Issue by jicowan** [christopherhein/eniconfig-controller#8]
Since the subnet in the ENIConfig needs to be in the same subnet as the worker node, we need to add logic to verify the subnet is valid choice for the worker node that the ENIConfig is assigned to. You can get the AZ of the worker node by calling the DescribeInstance API.  There's another API for getting the AZ of a subnet.  If they match, the ENIConfig is valid.

**Comment by jicowan** [comment]
Log an error and don't annotate.

**Comment by christopherhein** [comment]
Alright and the check when we get a new node check the AZ it’s in which I have from the `ProviderID` then loop through the ENIConfig and grab the one that the instance is tagged with, then check if `Spec.Subnet` Matches the subnet the instance is in. Log if it’s not and annotate if it is, right?

**Comment by jicowan** [comment]
That's right.
